---- Base app schema

-- User
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    username varchar(128) NOT NULL UNIQUE,

    -- Auth
    pwd varchar(256),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
    token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

-- Vendor
CREATE TABLE vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    name varchar(128) NOT NULL UNIQUE,

    contact_name varchar(128),
    contact_email varchar(128),
    contact_phone varchar(128)

);