# Cargo config
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environmaent variables
[env]

# Scope down tracing
RUST_LOG="rust_axum_course=trace"
PORT="8080"

# -- Service Environment Variables
# IMPORTANT: 
#   For Cargo commands only
#   For deployed env, should be managed by container
#   (e.g., Kubernetes).

## -- Secrets
SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"


## -- CinfigMap

SERVICE_WEB_FOLDER="http-root/"
